services:
  frontend:
    container_name: yourtradebase_frontend
    image: yourtradebase_i
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3333:5173
    